import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import mongoose from 'mongoose';
import Product from '../models/Product.js';
import { getProductImages } from './productImages.js';
import { SHOP_CATEGORIES, MIN_PRODUCTS_PER_CATEGORY } from '../constants/categories.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '../.env') });

const p = (item) => ({
  ...item,
  isActive: true,
  specs: item.specs || {},
  images: item.images?.length ? item.images : getProductImages(item.slug),
});

const products = [
  p({"name":"Apple iPhone 15 (128 GB) — Black","slug":"iphone-15-128gb-black","description":"6.1-inch Super Retina display, A16 Bionic chip, dual camera, 5G. Made for India with dual SIM support.","price":69999,"comparePrice":79900,"brand":"Apple","stock":42,"rating":4.7,"numReviews":12453,"featured":true,"prime":true,"bestseller":true,"dealLabel":"#1 Best Seller","specs":{"Storage":"128 GB","Colour":"Black","Warranty":"1 Year"},"features":["DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities so you don’t miss them while you’re doing something else.","INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design.","ALL-NEW 48MP MAIN CAMERA — The Main camera shoots in super-high resolution, making it easier than ever to take standout photos.","A16 BIONIC POWERHOUSE — The superfast and ultra-efficient A16 Bionic chip powers advanced features like computational photography and fluid Dynamic Island transitions."],"category":"Electronics"}),
  p({"name":"Samsung Galaxy S24 Ultra 5G","slug":"samsung-galaxy-s24-ultra","description":"200MP camera, S Pen, titanium frame, 5000mAh battery. Supports Indian 5G bands.","price":124999,"comparePrice":134999,"brand":"Samsung","stock":28,"rating":4.6,"numReviews":8921,"featured":true,"prime":true,"bestseller":true,"dealLabel":"Limited time deal","features":["GALAXY AI IS HERE — Unleash new levels of creativity, productivity and possibility with Galaxy AI.","200MP. DETAILS THAT RIVAL REALITY — Capture stunning details with the highest megapixel camera on a smartphone and AI processing that improves every picture.","BUILT WITH TITANIUM — Experience the strength of titanium built right into the frame for supreme durability.","BUILT-IN S PEN — Write, tap, and navigate with the precision your fingers wish they had on the new flat display."],"category":"Electronics"}),
  p({"name":"Sony WH-1000XM5 Wireless Headphones","slug":"sony-wh1000xm5-headphones","description":"Best-in-class noise cancellation, 30-hour battery, multipoint Bluetooth.","price":26990,"comparePrice":34990,"brand":"Sony","stock":156,"rating":4.8,"numReviews":23441,"featured":true,"prime":true,"bestseller":true,"dealLabel":"BuyZO's Choice","features":["INDUSTRY LEADING NOISE CANCELLATION — Two processors control 8 microphones for unprecedented noise cancellation.","EXCEPTIONAL SOUND QUALITY — Engineered to perfection with the new Integrated Processor V1.","CRYSTAL CLEAR HANDS-FREE CALLING — 4 beamforming microphones, precise voice pickup, and advanced audio signal processing.","UP TO 30-HOUR BATTERY LIFE — With quick charging (3 min charge for 3 hours of playback)."],"category":"Electronics"}),
  p({"name":"MacBook Air M3 13\" Laptop","slug":"macbook-air-m3-13","description":"Apple M3, 8GB RAM, 256GB SSD, up to 18 hours battery. Ideal for students & professionals.","price":99900,"comparePrice":114900,"brand":"Apple","stock":35,"rating":4.9,"numReviews":5621,"featured":true,"prime":true,"features":["LEAN. MEAN. M3 MACHINE — The blazing-fast MacBook Air with the M3 chip is a superportable laptop that sails through work and play.","PORTABLE DESIGN — Lightweight and under half an inch thin, so you can take MacBook Air anywhere you go.","UP TO 18 HOURS OF BATTERY LIFE — Go all day without a power adapter thanks to the power-efficient design of the Apple M3 chip.","BRILLIANT DISPLAY — The 13.6-inch Liquid Retina display supports 1 billion colors."],"category":"Electronics"}),
  p({"name":"Fire TV Stick 4K Max","slug":"fire-tv-stick-4k-max","description":"Stream Netflix, Prime Video, Hotstar & more. Alexa voice remote included.","price":4999,"comparePrice":7499,"brand":"Amazon","stock":500,"rating":4.5,"numReviews":89234,"featured":true,"prime":true,"bestseller":true,"dealLabel":"33% off","features":["OUR MOST POWERFUL STREAMING STICK — Elevate your entertainment experience with a powerful processor for lightning-fast app starts and fluid navigation.","LIFELIKE PICTURE AND SOUND — Enjoy show-stopping 4K Ultra HD, with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio.","WI-FI 6E SUPPORT — Enjoy smoother 4K streaming, even when multiple devices are connected to your router.","DO MORE WITH YOUR SMART HOME — Control compatible devices like cameras, lights, and more with your remote."],"category":"Electronics"}),
  p({"name":"Kindle Paperwhite (16 GB)","slug":"kindle-paperwhite-16gb","description":"6.8\" glare-free display, adjustable warm light, waterproof, weeks of battery.","price":12999,"comparePrice":16999,"brand":"Amazon","stock":200,"rating":4.7,"numReviews":45123,"prime":true,"bestseller":true,"features":["PURPOSE-BUILT FOR READING — With a flush-front design and 300 ppi glare-free display that reads like real paper, even in bright sunlight.","MORE READING TIME — A single charge via USB-C last weeks, not hours.","WATERPROOF READING — Built to withstand accidental immersion in water, so you are good from the beach to the bath.","ADJUSTABLE WARM LIGHT — Now with adjustable warm light to shift screen shade from white to amber."],"category":"Electronics"}),
  p({"name":"Logitech MX Master 3S Mouse","slug":"logitech-mx-master-3s","description":"Quiet clicks, USB-C charging, works on any surface including glass.","price":7495,"comparePrice":9995,"brand":"Logitech","stock":88,"rating":4.6,"numReviews":12340,"prime":true,"features":["ANY-SURFACE TRACKING — Now with an 8K DPI optical sensor that tracks anywhere, even on glass.","QUIET CLICKS — Creates 90% less click noise while maintaining the same satisfying click feel.","MAGSPEED SCROLLING — A computer mouse with remarkable speed, precision, and near silence.","MULTI-DEVICE — Pair with up to 3 devices via Bluetooth or the included Logi Bolt USB receiver."],"category":"Electronics"}),
  p({"name":"Anker 737 Power Bank 24000mAh","slug":"anker-737-power-bank","description":"140W fast charging for laptops & phones. BIS certified for India.","price":8999,"comparePrice":12999,"brand":"Anker","stock":120,"rating":4.5,"numReviews":8765,"prime":true,"dealLabel":"Deal of the Day","features":["ULTRA-POWERFUL TWO-WAY CHARGING — Equipped with the latest Power Delivery 3.1 and bi-directional technology to quickly recharge the portable charger or get a 140W ultra-powerful charge.","HIGH CAPACITY — Featuring a 24,000mAh battery capacity, juice up an iPhone 13 almost 5 times or a 2021 iPad Pro 12.9\" 1.3 times.","SMART DIGITAL DISPLAY — Easy-to-read digital display shows the output and input power and estimated time for the portable charger to fully recharge.","WHAT YOU GET — Anker 737 Power Bank, 140W USB-C to USB-C cable, welcome guide."],"category":"Electronics"}),
  p({"name":"boAt Airdopes 131 Wireless Earbuds","slug":"boat-airdopes-131","description":"13mm drivers, 15h playback with case, IPX4. Made for India.","price":999,"comparePrice":2990,"brand":"boAt","stock":600,"rating":4.3,"numReviews":234000,"prime":true,"bestseller":true,"dealLabel":"67% off","features":["PLAYBACK — Airdopes 131 offers a nonstop playback of up to 3H with each charge and an additional 12H playtime with the included charging case.","IWP TECHNOLOGY — The Insta Wake N’ Pair technology lets you seamlessly pair the earbuds the moment you open the case lid.","DRIVERS — It possesses 13mm drivers, for an enthralling audio experience.","IP RATING — The earbuds are marked with IPX4 water resistance."],"category":"Electronics"}),
  p({"name":"Redmi 43\" Smart LED TV 4K","slug":"redmi-smart-tv-43","description":"Android TV, Dolby Audio, multiple HDMI ports. 220V Indian model.","price":24999,"comparePrice":32999,"brand":"Redmi","stock":40,"rating":4.4,"numReviews":18900,"prime":true,"featured":true,"features":["RESOLUTION — 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 hertz | 178 Degree wide viewing angle.","SMART TV FEATURES — Android TV 10 | PatchWall 4 with IMDb integration | Quad core processor | Built-in Wi-Fi | Chromecast built-in.","SOUND — 30 Watts Output | Dolby Audio | DTS Virtual: X | Dolby Atmos pass through eARC.","CONNECTIVITY — 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports."],"category":"Electronics"}),
  p({"name":"Levi's 501 Original Fit Jeans","slug":"levis-501-original-jeans","description":"Classic straight fit, 100% cotton denim. Available in multiple waist sizes.","price":3499,"comparePrice":4999,"brand":"Levi's","stock":200,"rating":4.4,"numReviews":34521,"prime":true,"bestseller":true,"features":["MATERIAL — 100% Cotton, Non-Stretch Denim.","FIT — Regular fit through the thigh with a straight leg.","CLASSIC STYLING — The original blue jean since 1873 with the signature button fly.","CARE — Machine wash cold, tumble dry medium."],"category":"Fashion"}),
  p({"name":"Nike Air Max 90 Shoes","slug":"nike-air-max-90","description":"Iconic Air Max cushioning, durable outsole. UK/India sizing chart on product page.","price":9995,"comparePrice":12995,"brand":"Nike","stock":75,"rating":4.7,"numReviews":18932,"featured":true,"prime":true,"bestseller":true,"features":["COMFORT — Max Air cushioning in the heel delivers all-day comfort.","DURABILITY — Solid rubber waffle outsole maximizes traction and durability while still being lightweight.","STYLE — Iconic 90s aesthetic with stitched overlays and TPU accents.","BREATHABILITY — Mesh details on the upper keep your feet cool."],"category":"Fashion"}),
  p({"name":"Adidas Ultraboost Light","slug":"adidas-ultraboost-light","description":"LightBOOST midsole, breathable Primeknit upper for Indian weather.","price":8999,"comparePrice":15999,"brand":"Adidas","stock":60,"rating":4.6,"numReviews":7654,"prime":true,"dealLabel":"44% off","features":["LIGHTBOOST — The lightest Ultraboost ever made, with 30% lighter BOOST material.","PRIMEKNIT UPPER — Hugs the foot for a supportive, sock-like fit that breathes easily.","CONTINENTAL RUBBER — Outsole provides extraordinary traction in wet and dry conditions.","SUSTAINABLE — Made in part with recycled materials."],"category":"Fashion"}),
  p({"name":"Fossil Gen 6 Smartwatch","slug":"fossil-gen-6-smartwatch","description":"Wear OS, heart rate, SpO2, contactless pay. Compatible with Android & iOS.","price":14995,"comparePrice":24995,"brand":"Fossil","stock":45,"rating":4.3,"numReviews":4321,"prime":true,"features":["PERFORMANCE — Powered with Wear OS by Google and the Snapdragon Wear 4100+ platform.","HEALTH & FITNESS — Track your sleep history, monitor your restfulness, and set sleep goals. Built-in GPS for distance tracking.","CONNECTIVITY — Bluetooth 5.0, Wi-Fi, NFC, and GPS. Receive or make calls directly on your watch.","BATTERY — Charge up to 80% in just over 30 minutes."],"category":"Fashion"}),
  p({"name":"Men's Cotton Hoodie","slug":"mens-cotton-hoodie","description":"Soft fleece fabric, kangaroo pocket. Perfect for winter across India.","price":899,"comparePrice":1499,"brand":"BuyZO Basics","stock":300,"rating":4.5,"numReviews":67890,"prime":true,"bestseller":true,"features":["FABRIC — 60% Cotton, 40% Polyester blended fleece for warmth and softness.","DESIGN — Classic pullover styling with a roomy kangaroo front pocket.","FIT — Regular fit provides a comfortable, relaxed feel.","CARE — Easy to maintain; machine wash with like colors."],"category":"Fashion"}),
  p({"name":"Women's Cotton Kurti (Pack of 2)","slug":"womens-cotton-kurti","description":"Soft breathable cotton kurtis for daily wear. Multiple colours. Easy wash & iron.","price":1299,"comparePrice":1999,"brand":"BuyZO Basics","stock":180,"rating":4.3,"numReviews":12450,"prime":true,"features":["MATERIAL — 100% Pure breathable cotton, perfect for the Indian summer.","DESIGN — Elegant printed patterns with a comfortable straight fit.","VERSATILE — Can be paired with leggings, jeans, or palazzos for ethnic or casual looks.","CARE — Machine wash separately in cold water."],"category":"Fashion"}),
  p({"name":"Puma Suede Classic Sneakers","slug":"puma-suede-classic","description":"Timeless suede design, comfortable fit. Available in various colors.","price":4499,"comparePrice":6999,"brand":"Puma","stock":120,"rating":4.5,"numReviews":14231,"prime":true,"features":["MATERIAL — High-quality suede upper for a premium look and feel.","CUSHIONING — Padded collar and tongue for maximum comfort.","DURABILITY — Rubber outsole provides excellent grip and traction.","STYLE — The iconic Puma Formstrip on the lateral and medial sides."],"category":"Fashion"}),
  p({"name":"Ray-Ban Aviator Sunglasses","slug":"ray-ban-aviator","description":"Classic metal frame, 100% UV protection. Includes case and cleaning cloth.","price":7990,"comparePrice":9990,"brand":"Ray-Ban","stock":85,"rating":4.7,"numReviews":9876,"prime":true,"bestseller":true,"features":["PROTECTION — Lenses provide 100% UV protection to keep your eyes safe.","DESIGN — The timeless aviator teardrop shape that started it all.","MATERIAL — Durable metal frame that is lightweight and comfortable.","ACCESSORIES — Comes with a protective case and lens cloth."],"category":"Fashion"}),
  p({"name":"Casio G-Shock Men's Watch","slug":"casio-g-shock-watch","description":"Shock resistant, 200m water resistant, EL backlight. Tough and durable.","price":5995,"comparePrice":7495,"brand":"Casio","stock":150,"rating":4.8,"numReviews":21543,"prime":true,"features":["DURABILITY — Shock resistant construction protects against impact and vibration.","WATER RESISTANCE — 200-meter water resistance, suitable for professional marine activity.","FEATURES — Multi-function alarm, 1/100-second stopwatch, countdown timer.","DISPLAY — Electro-luminescent backlight with afterglow for easy reading in the dark."],"category":"Fashion"}),
  p({"name":"Biba Women's Salwar Suit Set","slug":"biba-salwar-suit-set","description":"Elegant embroidered suit set with dupatta. Perfect for festive occasions.","price":2499,"comparePrice":4999,"brand":"Biba","stock":65,"rating":4.4,"numReviews":5432,"prime":true,"dealLabel":"50% off","features":["MATERIAL — Premium cotton blend for a comfortable and rich feel.","DESIGN — Intricate embroidery work on the kurta with matching bottom and dupatta.","FIT — Available in standard sizes with a flattering silhouette.","OCCASION — Ideal for festivals, weddings, and traditional gatherings."],"category":"Fashion"}),
  p({"name":"Instant Pot Duo 7-in-1 (3L)","slug":"instant-pot-duo-7in1","description":"Pressure cook, slow cook, rice, steam & more. 220V for Indian kitchens.","price":6499,"comparePrice":8999,"brand":"Instant Pot","stock":90,"rating":4.7,"numReviews":156789,"featured":true,"prime":true,"bestseller":true,"dealLabel":"#1 Best Seller","features":["7-IN-1 FUNCTIONALITY — Pressure cook, slow cook, rice cooker, yogurt maker, steamer, sauté pan and food warmer.","QUICK ONE-TOUCH COOKING — 13 customizable Smart Programs for pressure cooking ribs, soups, beans, rice, poultry, yogurt, desserts and more.","COOK FAST OR SLOW — Pressure cook delicious one-pot meals up to 70% faster than traditional cooking methods.","SAFETY FEATURES — Includes over 10 safety features, plus overheat protection and safe-locking lid."],"category":"Home & Kitchen"}),
  p({"name":"Ninja Blender 1000W","slug":"ninja-professional-blender","description":"Crush ice & make lassi, smoothies, chutneys. Dishwasher-safe jars.","price":5499,"comparePrice":7499,"brand":"Ninja","stock":110,"rating":4.6,"numReviews":89234,"prime":true,"bestseller":true,"features":["POWERFUL MOTOR — 1000 watts of professional performance power.","TOTAL CRUSHING TECHNOLOGY — Crushes ice, whole fruits, and vegetables in seconds.","LARGE CAPACITY — 72 oz. professional blender pitcher is excellent for making frozen drinks and creamy smoothies for the entire family.","EASY TO CLEAN — Pitcher, lid, and blades are dishwasher safe."],"category":"Home & Kitchen"}),
  p({"name":"Dyson V15 Cordless Vacuum","slug":"dyson-v15-detect-vacuum","description":"Laser dust detect, 60 min runtime, HEPA filter for Indian dust & pollen.","price":54990,"comparePrice":62990,"brand":"Dyson","stock":25,"rating":4.5,"numReviews":12345,"prime":true,"featured":true,"features":["LASER REVEALS MICROSCOPIC DUST — A precisely-angled laser makes invisible dust visible on hard floors.","SCIENTIFIC PROOF OF A DEEP CLEAN — The LCD screen shows what’s been sucked up, displaying real-time scientific proof of a deep clean.","POWERFUL SUCTION — The Dyson Hyperdymium motor spins at up to 125,000rpm to generate powerful suction.","ADVANCED FILTRATION — Dyson’s fully-sealed, six-stage filtration traps 99.99% of particles as small as 0.3 microns."],"category":"Home & Kitchen"}),
  p({"name":"Prestige Coffee Maker","slug":"prestige-coffee-maker","description":"Filter coffee & espresso-style brew. 220V, auto shut-off, Indian plug.","price":3999,"comparePrice":5999,"brand":"Prestige","stock":70,"rating":4.4,"numReviews":45678,"prime":true,"features":["FROTHING NOZZLE — Comes with a frothing nozzle to make the perfect cappuccino.","EASY TO CLEAN — Detachable drip tray makes cleaning a breeze.","SAFETY — Built-in auto shut-off feature ensures safety and saves energy.","CAPACITY — Brews up to 4 cups of coffee simultaneously."],"category":"Home & Kitchen"}),
  p({"name":"Wakefit Orthopedic Mattress Queen","slug":"wakefit-mattress-queen","description":"High-density foam, 7-zone support. 100 nights trial, 10-year warranty in India.","price":8999,"comparePrice":12999,"brand":"Wakefit","stock":15,"rating":4.6,"numReviews":9876,"prime":false,"features":["ORTHOPEDIC SUPPORT — High-resilience foam provides firm support for your back and aligns the spine.","BREATHABLE FABRIC — Premium quality breathable fabric cover keeps you cool during sleep.","MOTION ISOLATION — Minimizes motion transfer, ensuring undisturbed sleep if your partner moves.","WARRANTY & TRIAL — Comes with a 10-year manufacturer warranty and a 100-night trial."],"category":"Home & Kitchen"}),
  p({"name":"Prestige Pressure Cooker 5L (Induction)","slug":"prestige-pressure-cooker-5l","description":"Stainless steel, 5-litre capacity, induction & gas compatible. ISI certified for India.","price":2499,"comparePrice":3499,"brand":"Prestige","stock":95,"rating":4.6,"numReviews":45600,"prime":true,"bestseller":true,"features":["MATERIAL — Made from high-quality stainless steel for durability and hygiene.","INDUCTION BASE — Features an induction base for versatile cooking on gas and induction cooktops.","SAFETY — Comes with a metallic safety plug and a precision weight valve.","CAPACITY — 5-litre capacity is ideal for cooking meals for 5-7 people."],"category":"Home & Kitchen"}),
  p({"name":"Philips Air Fryer XL","slug":"philips-air-fryer-xl","description":"Fry, bake, grill, roast with 90% less fat. Rapid Air Technology.","price":8999,"comparePrice":11995,"brand":"Philips","stock":140,"rating":4.7,"numReviews":32145,"prime":true,"features":["RAPID AIR TECHNOLOGY — Unique starfish design swirls hot air to create delicious foods that are crispy on the outside and tender on the inside.","HEALTHY FRYING — Fry with up to 90% less fat compared to traditional deep frying.","XL CAPACITY — 1.2Kg capacity basket, combined with the 6.2L pan, helps you cook a variety of meals for up to 5 people.","TOUCH SCREEN — Digital touch screen with 7 presets for easy cooking."],"category":"Home & Kitchen"}),
  p({"name":"Milton Thermosteel Water Bottle 1L","slug":"milton-thermosteel-bottle","description":"Vacuum insulated stainless steel flask. Keeps water hot or cold for 24 hours.","price":899,"comparePrice":1250,"brand":"Milton","stock":450,"rating":4.5,"numReviews":87654,"prime":true,"bestseller":true,"features":["INSULATION — Double-walled vacuum insulation keeps beverages hot or cold for 24 hours.","MATERIAL — Made from 18/8 food-grade stainless steel inside and out.","LEAK PROOF — Comes with a leak-proof lid and a copper coating for better heat retention.","PORTABLE — Rust-proof and easy to carry for school, office, or travel."],"category":"Home & Kitchen"}),
  p({"name":"Pigeon Chopper Pro","slug":"pigeon-chopper-pro","description":"Manual handy vegetable chopper with 3 stainless steel blades.","price":299,"comparePrice":595,"brand":"Pigeon","stock":600,"rating":4.3,"numReviews":123456,"prime":true,"features":["BLADES — 3 sharp stainless steel blades for quick and effortless chopping.","MATERIAL — Made from unbreakable ABS plastic for long-lasting use.","EASY TO USE — Simple pull-cord mechanism requires no electricity.","EASY TO CLEAN — Completely detachable base, blades, and lid for easy cleaning."],"category":"Home & Kitchen"}),
  p({"name":"Solimo Microfibre Comforter Double","slug":"solimo-comforter-double","description":"Reversible, lightweight, cozy AC blanket. Machine washable.","price":1499,"comparePrice":2500,"brand":"Amazon Brand - Solimo","stock":250,"rating":4.6,"numReviews":45612,"prime":true,"features":["SOFT & COZY — Made from 100% microfibre shell for a rich and luxurious feel.","REVERSIBLE DESIGN — Two-tone reversible design to match different room decors.","LIGHTWEIGHT — 200 GSM hollow siliconized polyester filling, perfect for everyday use and AC rooms.","EASY CARE — Machine stitched pattern keeps the filling in place for durability. Machine washable."],"category":"Home & Kitchen"}),
  p({"name":"Adjustable Dumbbells Pair 24kg","slug":"adjustable-dumbbells-24kg","description":"Home gym essential, quick weight change 2–24 kg per hand.","price":34999,"comparePrice":44999,"brand":"BuyZO Sport","stock":20,"rating":4.8,"numReviews":23456,"prime":true,"featured":true,"features":["EASY ADJUSTMENT — Adjust weights from 2kg to 24kg per dumbbell with a simple turn of the dial.","SPACE SAVING — Replaces 15 sets of weights, providing a versatile workout while saving space in your home gym.","DURABLE MOLDING — Durable molding around metal plates provides for a smooth lift-off and quieter workouts.","ERGONOMIC GRIP — Premium grip handle for comfortable, secure lifting."],"category":"Sports"}),
  p({"name":"Yoga Mat 6mm Anti-Slip","slug":"yoga-mat-6mm","description":"Extra thick, sweat-resistant, carry strap included. For yoga & exercise at home.","price":999,"comparePrice":1999,"brand":"Strauss","stock":55,"rating":4.7,"numReviews":8765,"prime":true,"features":["PREMIUM MATERIAL — Made from high-density EVA material for maximum comfort and durability.","ANTI-SLIP TEXTURE — Double-sided non-slip surfaces help prevent injuries and hold poses firmly.","EXTRA THICK — 6mm thickness provides excellent cushioning for joints during hard floor routines.","PORTABLE — Comes with a convenient carry strap for easy transport to the studio or gym."],"category":"Sports"}),
  p({"name":"Fitbit Charge 6","slug":"fitbit-charge-6","description":"GPS, heart rate, sleep score, 7-day battery. Works with Google Fit.","price":9999,"comparePrice":14999,"brand":"Fitbit","stock":95,"rating":4.4,"numReviews":15432,"prime":true,"dealLabel":"33% off","features":["HEART RATE TRACKING — The most accurate heart rate tracking on a Fitbit tracker yet.","GOOGLE ESSENTIALS — Includes Google Maps, Google Wallet, and YouTube Music controls.","BUILT-IN GPS — See your pace and distance on your wrist without your phone.","BATTERY LIFE — Up to 7 days of battery life, so you can track day and night."],"category":"Sports"}),
  p({"name":"Nivia Basketball Size 7","slug":"nivia-basketball","description":"Official size 7, moisture grip, deep channels. Popular in schools & colleges.","price":899,"comparePrice":1299,"brand":"Nivia","stock":140,"rating":4.8,"numReviews":5432,"prime":true,"features":["OFFICIAL SIZE & WEIGHT — Size 7 basketball, suitable for men and boys ages 15 and up.","SUPERIOR GRIP — Rubber cover with a pebbled texture provides excellent grip and control.","DURABILITY — Built for competitive indoor and outdoor play.","DEEP CHANNELS — Deep channel design for better dribbling and shooting alignment."],"category":"Sports"}),
  p({"name":"English Willow Cricket Bat (Full Size)","slug":"cricket-bat-willow","description":"Light pick-up, Kashmir/English willow blend. Popular for tennis-ball & leather-ball cricket.","price":1999,"comparePrice":2999,"brand":"SG","stock":65,"rating":4.5,"numReviews":8900,"prime":true,"features":["MATERIAL — Made from premium quality willow for durability and performance.","HANDLE — Cane handle with a rubber grip for shock absorption and comfort.","PROFILE — Thick edges and a pronounced bow for improved sweet spot and power.","VERSATILE — Suitable for both tennis ball and leather ball play."],"category":"Sports"}),
  p({"name":"Resistance Bands Set (5 Levels)","slug":"resistance-bands-set","description":"Home workout bands with handles & door anchor. Great for strength training.","price":699,"comparePrice":1299,"brand":"BuyZO Sport","stock":220,"rating":4.4,"numReviews":15600,"prime":true,"features":["5 RESISTANCE LEVELS — Color-coded bands ranging from 10 lbs to 50 lbs, stackable up to 150 lbs.","PREMIUM QUALITY — Made of natural latex that is snap-resistant and durable.","COMPLETE SET — Includes 5 bands, 2 cushioned handles, 2 ankle straps, a door anchor, and a carry bag.","VERSATILE WORKOUTS — Perfect for muscle building, fat burning, physical therapy, and home gym workouts."],"category":"Sports"}),
  p({"name":"Yonex Badminton Racquet Mavis 350","slug":"yonex-badminton-racquet","description":"Lightweight aluminium racquet with 6 nylon shuttlecocks.","price":1299,"comparePrice":1899,"brand":"Yonex","stock":300,"rating":4.6,"numReviews":23145,"prime":true,"features":["FRAME MATERIAL — Lightweight aluminium frame for easy handling and quick swings.","SHAFT — Steel shaft for durability and solid impact.","SHUTTLECOCKS INCLUDED — Comes with a tube of 6 Mavis 350 nylon shuttlecocks.","IDEAL FOR BEGINNERS — Designed for recreational players and beginners for comfortable play."],"category":"Sports"}),
  p({"name":"Nivia Football Size 5","slug":"nivia-football-size-5","description":"Water resistant, hand stitched, official size and weight.","price":799,"comparePrice":1099,"brand":"Nivia","stock":180,"rating":4.5,"numReviews":12345,"prime":true,"features":["CONSTRUCTION — 32 panel hand-stitched construction for durability and shape retention.","MATERIAL — High-quality synthetic rubber outer material for excellent touch and feel.","WATER RESISTANT — Suitable for play in all weather conditions, including hard grounds.","BLADDER — Latex bladder provides excellent air retention and bounce."],"category":"Sports"}),
  p({"name":"Firefox Mountain Bike 27.5T","slug":"firefox-mountain-bike","description":"21-speed Shimano gears, dual disc brakes, alloy frame.","price":15999,"comparePrice":20999,"brand":"Firefox","stock":25,"rating":4.3,"numReviews":890,"prime":false,"features":["GEAR SYSTEM — 21-speed Shimano Tourney gearing for smooth shifting on different terrains.","BRAKES — Powerful dual mechanical disc brakes for reliable stopping power.","FRAME — Lightweight and sturdy aluminium alloy frame for agility and durability.","SUSPENSION — Front suspension fork to absorb shocks from rough trails."],"category":"Sports"}),
  p({"name":"Boldfit Skipping Rope","slug":"boldfit-skipping-rope","description":"Adjustable length, tangle-free, foam handles for cardio workout.","price":199,"comparePrice":399,"brand":"Boldfit","stock":500,"rating":4.4,"numReviews":45678,"prime":true,"bestseller":true,"features":["TANGLE FREE — Smooth PVC cable ensures a tangle-free jumping experience.","ADJUSTABLE LENGTH — Easy to adjust the 9.8-foot cable to suit your height.","COMFORT GRIP — Ergonomically designed handles covered with soft EVA foam for a comfortable, non-slip grip.","SMOOTH ROTATION — Premium ball bearings ensure fast and smooth rotation without twisting."],"category":"Sports"}),
  p({"name":"CeraVe Moisturizing Cream 340g","slug":"cerave-moisturizing-cream","description":"Hyaluronic acid & ceramides. Dermatologist recommended for Indian skin.","price":899,"comparePrice":1199,"brand":"CeraVe","stock":400,"rating":4.7,"numReviews":98765,"prime":true,"bestseller":true,"dealLabel":"#1 Best Seller","features":["ESSENTIAL CERAMIDES — Contains 3 essential ceramides (1, 3, 6-II) to help restore the protective skin barrier.","HYALURONIC ACID — Formulated with hyaluronic acid to help retain skin’s natural moisture.","MVE TECHNOLOGY — Patented delivery system continually releases moisturizing ingredients for 24-hour hydration.","GENTLE ON SKIN — Fragrance-free, non-comedogenic, and suitable for dry to very dry skin on the face and body."],"category":"Beauty"}),
  p({"name":"Hair Repair Treatment 100ml","slug":"hair-repair-treatment","description":"Repairs damaged hair from heat & pollution. Use once a week.","price":1299,"comparePrice":1799,"brand":"L'Oreal","stock":180,"rating":4.6,"numReviews":34567,"prime":true,"bestseller":true,"features":["DEEP REPAIR — Penetrates the hair shaft to repair damage caused by heat, styling, and environmental factors.","STRENGTHENS — Fortifies hair to prevent breakage and split ends, leaving hair visibly healthier.","ADDS SHINE — Smooths the hair cuticle for a brilliant, glossy finish without weighing hair down.","EASY APPLICATION — Apply to damp hair once a week, leave for 5-10 minutes, and rinse thoroughly."],"category":"Beauty"}),
  p({"name":"Philips Electric Toothbrush","slug":"philips-electric-toothbrush","description":"Sonic clean, 2 modes, 2-week battery. Includes 2 brush heads.","price":2999,"comparePrice":4499,"brand":"Philips","stock":65,"rating":4.5,"numReviews":21345,"prime":true,"features":["SONIC TECHNOLOGY — Pulses fluid between your teeth and along the gumline for a gentle and effective clean.","PLAQUE REMOVAL — Removes up to 3x more plaque than a manual toothbrush.","SMARTIMER — Built-in 2-minute timer ensures you brush for the dentist-recommended time.","BATTERY LIFE — A single charge provides up to 14 days of regular use."],"category":"Beauty"}),
  p({"name":"Lakmé Face Wash 100ml","slug":"lakme-face-wash-100ml","description":"Deep cleanse for Indian skin types. Removes oil & pollution without over-drying.","price":249,"comparePrice":349,"brand":"Lakmé","stock":500,"rating":4.5,"numReviews":67800,"prime":true,"features":["DEEP CLEANSING — Effectively removes dirt, oil, and pollution from deep within the pores.","NON-DRYING FORMULA — Cleanses thoroughly without stripping the skin of its natural moisture.","FRESH GLOW — Leaves skin feeling refreshed, soft, and visibly radiant.","SUITABLE FOR ALL — Dermatologically tested and suitable for all Indian skin types."],"category":"Beauty"}),
  p({"name":"Nivea Body Lotion 400ml","slug":"nivea-body-lotion-400ml","description":"24h moisture for dry skin. Non-greasy formula suited to humid Indian climates.","price":349,"comparePrice":499,"brand":"Nivea","stock":420,"rating":4.6,"numReviews":89000,"prime":true,"bestseller":true,"features":["INTENSE MOISTURE — Enriched with almond oil and Vitamin E for 24 hours of deep moisture.","NON-GREASY — Fast-absorbing formula that doesn't leave a sticky residue, perfect for humid climates.","NOURISHES — Repairs dry and damaged skin, leaving it noticeably smoother.","EVERYDAY USE — Ideal for daily application after a shower for the best results."],"category":"Beauty"}),
  p({"name":"Maybelline Colossal Mascara","slug":"maybelline-mascara","description":"Volumizing mascara, smudge-resistant for all-day wear in heat & humidity.","price":499,"comparePrice":699,"brand":"Maybelline","stock":310,"rating":4.4,"numReviews":34500,"prime":true,"features":["INSTANT VOLUME — Collagen-infused formula delivers colossal volume instantly without clumping.","MEGA BRUSH — The iconic Mega Brush coats every single lash from root to tip.","LONG LASTING — Smudge-resistant and waterproof for all-day wear, even in humid weather.","SAFE FOR EYES — Ophthalmologist tested, suitable for contact lens wearers."],"category":"Beauty"}),
  p({"name":"Cetaphil Gentle Skin Cleanser 250ml","slug":"cetaphil-skin-cleanser","description":"Hydrating face & body wash for sensitive, dry skin.","price":399,"comparePrice":550,"brand":"Cetaphil","stock":350,"rating":4.8,"numReviews":125000,"prime":true,"bestseller":true,"features":["GENTLE FORMULA — Clinically proven to deeply clean while leaving skin hydrated and calm.","SENSITIVE SKIN — Hypoallergenic, fragrance-free, and non-comedogenic, making it ideal for sensitive skin.","DEFENDS AGAINST SENSITIVITY — Protects against the 5 signs of skin sensitivity: dryness, irritation, roughness, tightness, and a weakened skin barrier.","MULTI-USE — Can be used with or without water for face and body cleansing."],"category":"Beauty"}),
  p({"name":"Minimalist 10% Niacinamide Serum","slug":"minimalist-niacinamide-serum","description":"Reduces acne marks, blemishes & oiliness. 30ml.","price":599,"comparePrice":699,"brand":"Minimalist","stock":200,"rating":4.5,"numReviews":45678,"prime":true,"features":["ACNE CONTROL — 10% Niacinamide helps reduce acne marks, blemishes, and dark spots.","OIL BALANCE — Regulates sebum production, making it highly effective for oily and acne-prone skin.","CLEAN BEAUTY — Free from fragrance, silicones, sulfates, parabens, and essential oils.","FAST ABSORBING — Lightweight, non-sticky serum that absorbs quickly into the skin."],"category":"Beauty"}),
  p({"name":"Garnier Micellar Water 400ml","slug":"garnier-micellar-water","description":"Removes makeup, cleanses and soothes. No rinsing required.","price":349,"comparePrice":449,"brand":"Garnier","stock":450,"rating":4.6,"numReviews":54321,"prime":true,"features":["MAGNETIC ACTION — Micelles act like magnets to lift away dirt, oil, and makeup without harsh rubbing.","ALL-IN-ONE — Cleanses, removes makeup, and soothes skin in one easy step.","NO RINSING — Leaves skin perfectly clean and refreshed without the need to rinse.","GENTLE — Suitable for all skin types, including sensitive skin. Ophthalmologist tested."],"category":"Beauty"}),
  p({"name":"Olaplex No.7 Bonding Oil","slug":"olaplex-no7-oil","description":"Highly-concentrated, weightless styling oil. Heat protection up to 450°F.","price":2950,"comparePrice":3200,"brand":"Olaplex","stock":50,"rating":4.7,"numReviews":12345,"prime":true,"features":["REPAIRS — Dramatically increases shine, softness, and color vibrancy while repairing damaged hair.","HEAT PROTECTION — Provides heat protection up to 450°F (232°C).","WEIGHTLESS — Highly concentrated yet incredibly lightweight, so it won’t weigh hair down.","ALL HAIR TYPES — Suitable for all hair types and textures."],"category":"Beauty"}),
  p({"name":"The Psychology of Money (Paperback)","slug":"psychology-of-money-book","description":"Bestselling book on wealth & behaviour. English edition, Indian pricing.","price":399,"comparePrice":599,"brand":"Jaico","stock":250,"rating":4.8,"numReviews":67890,"prime":true,"bestseller":true,"features":["TIMELESS LESSONS — 19 short stories exploring the strange ways people think about money.","BEHAVIORAL FINANCE — Teaches you how to make better sense of one of life’s most important topics by understanding behavior, not just math.","EASY READ — Written in an engaging, jargon-free style accessible to everyone.","GLOBAL BESTSELLER — Millions of copies sold worldwide, highly recommended by financial experts."],"category":"Books"}),
  p({"name":"Atomic Habits — James Clear","slug":"atomic-habits-book","description":"Build good habits & break bad ones. #1 self-help book in India.","price":449,"comparePrice":799,"brand":"Penguin","stock":320,"rating":4.8,"numReviews":123456,"prime":true,"bestseller":true,"dealLabel":"44% off","features":["PROVEN FRAMEWORK — Offers a proven framework for improving every day, regardless of your goals.","PRACTICAL STRATEGIES — Learn practical strategies to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.","EASY TO UNDERSTAND — Distills complex topics from biology, psychology, and neuroscience into simple, actionable advice.","TRANSFORMATIONAL — Over 15 million copies sold, changing lives globally."],"category":"Books"}),
  p({"name":"Rich Dad Poor Dad (Paperback)","slug":"rich-dad-poor-dad-book","description":"Personal finance classic. Easy read for students & professionals in India.","price":350,"comparePrice":550,"brand":"Plata","stock":400,"rating":4.7,"numReviews":89000,"prime":true,"bestseller":true,"features":["FINANCIAL LITERACY — Explodes the myth that you need to earn a high income to become rich.","ASSETS VS LIABILITIES — Clearly defines the difference between an asset and a liability.","MINDSET SHIFT — Challenges the belief that your house is an asset and teaches what to teach your kids about money.","CLASSIC — The #1 Personal Finance book of all time."],"category":"Books"}),
  p({"name":"The Alchemist — Paulo Coelho","slug":"the-alchemist-book","description":"Inspirational fiction loved worldwide. English paperback, Indian edition.","price":299,"comparePrice":499,"brand":"Harper","stock":380,"rating":4.8,"numReviews":112000,"prime":true,"features":["INSPIRATIONAL STORY — Follows the journey of an Andalusian shepherd boy named Santiago in search of worldly treasure.","WISDOM — A story that teaches us about the essential wisdom of listening to our hearts, recognizing opportunity, and learning to read the omens strewn along life’s path.","GLOBAL PHENOMENON — Translated into 80 languages and has sold over 65 million copies worldwide.","TIMELESS — A modern classic that continues to inspire readers across generations."],"category":"Books"}),
  p({"name":"IKIGAI — The Japanese Secret","slug":"ikigai-book","description":"Find purpose & longevity habits. Bestseller in India.","price":399,"comparePrice":599,"brand":"Penguin","stock":290,"rating":4.7,"numReviews":56000,"prime":true,"features":["JAPANESE WISDOM — Explores the Japanese concept of Ikigai, meaning \"a reason to jump out of bed each morning\".","SECRETS TO LONGEVITY — Based on interviews with the residents of the Japanese village with the highest percentage of 100-year-olds.","PRACTICAL ADVICE — Provides practical tools to help you discover your own ikigai and bring meaning and joy to every day.","UPLIFTING — A comforting and inspiring read for anyone seeking purpose."],"category":"Books"}),
  p({"name":"Sapiens — Yuval Noah Harari","slug":"sapiens-book","description":"A brief history of humankind. Thought-provoking read for curious minds.","price":499,"comparePrice":799,"brand":"Penguin","stock":210,"rating":4.8,"numReviews":78000,"prime":true,"dealLabel":"38% off","features":["DEEP HISTORY — Spans the entire history of humankind, from the very first humans to the radical and devastating breakthroughs of the Cognitive, Agricultural, and Scientific Revolutions.","THOUGHT PROVOKING — Challenges everything we thought we knew about being human.","ENGAGING NARRATIVE — Written in an accessible and engaging style that makes complex history easy to digest.","CRITICALLY ACCLAIMED — Recommended by Barack Obama, Bill Gates, and Mark Zuckerberg."],"category":"Books"}),
  p({"name":"Do Epic Shit — Ankur Warikoo","slug":"do-epic-shit-book","description":"Thoughts on success, failure, habits, and money.","price":250,"comparePrice":399,"brand":"Juggernaut","stock":500,"rating":4.5,"numReviews":34567,"prime":true,"features":["RELATABLE ADVICE — Insights on success and failure from one of India's top entrepreneurs and content creators.","SHORT CHAPTERS — Designed to be read in short bursts, perfect for busy individuals.","PRACTICAL WISDOM — Covers topics like habits, money, relationships, and self-awareness.","HONEST REFLECTIONS — A raw and honest look at the author's own mistakes and learnings."],"category":"Books"}),
  p({"name":"Harry Potter and the Philosopher's Stone","slug":"harry-potter-1","description":"The book that started the magic. Special 25th anniversary edition.","price":399,"comparePrice":499,"brand":"Bloomsbury","stock":150,"rating":4.9,"numReviews":234567,"prime":true,"bestseller":true,"features":["MAGICAL BEGINNING — Experience the start of Harry's journey at Hogwarts School of Witchcraft and Wizardry.","UNFORGETTABLE CHARACTERS — Meet Ron, Hermione, Hagrid, and the rest of the beloved cast.","TIMELESS ADVENTURE — A story of friendship, bravery, and the battle between good and evil that captivates readers of all ages.","MUST READ — The essential first book in the global phenomenon series."],"category":"Books"}),
  p({"name":"Deep Work — Cal Newport","slug":"deep-work-book","description":"Rules for focused success in a distracted world.","price":350,"comparePrice":599,"brand":"Piatkus","stock":180,"rating":4.6,"numReviews":45678,"prime":true,"features":["FOCUS STRATEGIES — Learn how to focus without distraction on a cognitively demanding task.","INCREASE PRODUCTIVITY — Discover rules and habits to cultivate deep work and achieve massive productivity.","COMBAT DISTRACTIONS — Strategies to minimize the impact of social media, email, and other shallow tasks.","CAREER ADVANTAGE — Master the skill of deep work to thrive in the modern economy."],"category":"Books"}),
  p({"name":"Man's Search for Meaning","slug":"mans-search-for-meaning","description":"Viktor Frankl's classic memoir and psychological exploration.","price":220,"comparePrice":299,"brand":"Rider","stock":220,"rating":4.8,"numReviews":89012,"prime":true,"features":["PROFOUND MEMOIR — A gripping and moving account of Viktor Frankl's experiences in Nazi concentration camps.","LOGOTHERAPY — Introduces Frankl's theory of logotherapy, which argues that our primary drive is the pursuit of meaning.","FINDING PURPOSE — Offers profound lessons on finding meaning and hope even in the most horrific circumstances.","LIFE CHANGING — A classic work that continues to inspire millions to overcome adversity."],"category":"Books"}),
  p({"name":"LEGO Star Wars Millennium Falcon","slug":"lego-millennium-falcon","description":"1351 pieces, ages 9+. Great gift for kids — ships across India.","price":13999,"comparePrice":15999,"brand":"LEGO","stock":40,"rating":4.9,"numReviews":8765,"prime":true,"featured":true,"features":["ICONIC STARSHIP — Build a detailed model of the legendary Millennium Falcon from Star Wars: The Rise of Skywalker.","MINIFIGURES INCLUDED — Includes 7 LEGO Star Wars characters: Finn, Chewbacca, C-3PO, Lando Calrissian and Boolio minifigures, plus R2-D2 and D-O LEGO droid figures.","DETAILED INTERIOR — Features a fully equipped interior, including a cargo area, navigation computer, and hidden smuggling compartment.","1,351 PIECES — A challenging and rewarding build for boys and girls aged 9+."],"category":"Toys"}),
  p({"name":"Nerf Elite 2.0 Blaster","slug":"nerf-elite-commander","description":"6-dart drum, slam fire. Safe foam darts for children 8+.","price":999,"comparePrice":1499,"brand":"Nerf","stock":200,"rating":4.5,"numReviews":23456,"prime":true,"features":["UPGRADE-READY BLASTER — Customize the blaster for every battle or mission by taking advantage of 3 tactical rails and barrel and stock attachment points.","INCLUDES 12 NERF DARTS — Comes with 12 Official Nerf darts to fully load the 6-dart drum and 6 more darts so you're ready for reloads.","SLAM FIRE — Pull the priming slide back and press the trigger to fire 1 dart, or slam-fire all 6 darts rapidly by holding down the trigger and repeatedly moving the slide.","FIRES DARTS UP TO 90 FEET (27 METERS) — Go the distance with this blaster that fires darts up to 90 feet."],"category":"Toys"}),
  p({"name":"Barbie Dreamhouse Playset","slug":"barbie-dreamhouse-playset","description":"3-storey dollhouse with furniture & accessories. Ages 3+.","price":4999,"comparePrice":6999,"brand":"Barbie","stock":35,"rating":4.5,"numReviews":5600,"prime":true,"featured":true,"features":["3 STORIES OF FUN — Measuring 43 inches tall and 41 inches wide, this fully furnished Dreamhouse inspires endless imagination.","10 INDOOR & OUTDOOR PLAY AREAS — Features a pool, slide, working elevator, and a puppy play area.","CUSTOMIZABLE — Features customizable spaces and transforming furniture to create new scenes.","75+ ACCESSORIES — Includes over 75 storytelling pieces, featuring realistic touches and textures."],"category":"Toys"}),
  p({"name":"Monopoly India Edition Board Game","slug":"monopoly-india-edition","description":"Classic property game with Indian cities. Family game night favourite.","price":899,"comparePrice":1299,"brand":"Hasbro","stock":150,"rating":4.7,"numReviews":34000,"prime":true,"bestseller":true,"features":["INDIAN CITIES — Buy, sell, and trade iconic Indian cities and locations.","FAMILY FUN — A classic fast-dealing property trading game for 2 to 6 players, ages 8 and up.","LEARN TO NEGOTIATE — Teaches basic financial skills, negotiation, and strategy.","INCLUDES — Gameboard, 6 tokens, 28 Title Deed cards, 16 Chance cards, 16 Community Chest cards, 32 houses, 12 hotels, 2 dice, money pack, and instructions."],"category":"Toys"}),
  p({"name":"Rubik's Cube 3×3 (Speed Cube)","slug":"rubiks-cube-3x3","description":"Smooth-turning stickerless cube. Improves focus & problem-solving for kids & adults.","price":299,"comparePrice":499,"brand":"Rubik's","stock":400,"rating":4.6,"numReviews":28900,"prime":true,"features":["SMOOTH PLAY — Features an improved mechanism that results in smoother, faster, and more reliable play.","STICKERLESS — Traditional stickers have been replaced with plastic tiles, meaning no fading, peeling, or cheating.","BRAIN TEASER — A classic puzzle that improves cognitive skills, hand-eye coordination, and problem-solving.","FOR ALL AGES — A perfect toy for kids, teens, and adults."],"category":"Toys"}),
  p({"name":"Uno Card Game","slug":"uno-card-game","description":"Classic family card game of matching colors and numbers.","price":149,"comparePrice":199,"brand":"Mattel","stock":800,"rating":4.8,"numReviews":145000,"prime":true,"bestseller":true,"features":["CLASSIC FUN — The classic card game of matching colors and numbers that is easy to pick up and impossible to put down.","ACTION CARDS — Use action cards like Skips, Reverses, Draw Twos, and color-changing Wild cards to gain the advantage.","DON'T FORGET — When you're down to one card, don't forget to yell \"UNO!\"","FOR EVERYONE — Perfect for 2 to 10 players, ages 7 and older."],"category":"Toys"}),
  p({"name":"Play-Doh Modeling Compound 10-Pack","slug":"play-doh-10-pack","description":"Non-toxic, assorted colors. Sparks creativity for kids 2+.","price":499,"comparePrice":699,"brand":"Play-Doh","stock":250,"rating":4.7,"numReviews":34567,"prime":true,"features":["10 VIBRANT COLORS — Includes 10 cans of Play-Doh modeling compound in a variety of bright colors.","SPARKS CREATIVITY — Squishy, bright, non-toxic compound sparks imaginations for kids 2 and up.","REUSABLE CANS — Comes in 2-ounce cans to keep the compound fresh for next time.","NON-TOXIC — Safe, non-toxic formula (contains wheat)."],"category":"Toys"}),
  p({"name":"Hot Wheels 5-Car Pack","slug":"hot-wheels-5-pack","description":"1:64 scale die-cast vehicles. Assorted styles.","price":699,"comparePrice":899,"brand":"Hot Wheels","stock":300,"rating":4.8,"numReviews":45612,"prime":true,"features":["5 DIE-CAST CARS — Includes 5 Hot Wheels 1:64 scale die-cast vehicles in a unifying theme.","AUTHENTIC DETAILS — Each car features authentic styling and eye-catching decos.","COLLECTIBLE — A great starter set or addition to any Hot Wheels collection.","FOR KIDS & COLLECTORS — Appeals to kids and car enthusiasts of all ages."],"category":"Toys"}),
  p({"name":"Jenga Classic Game","slug":"jenga-classic","description":"The classic block-stacking, stack-crashing game.","price":799,"comparePrice":999,"brand":"Hasbro","stock":220,"rating":4.7,"numReviews":56789,"prime":true,"features":["CLASSIC JENGA — Pull out a block without crashing the stack to win at Jenga.","HARDWOOD BLOCKS — Includes 54 precision-crafted genuine hardwood blocks.","STACKING SLEEVE — Comes with a stacking sleeve to help build the tower perfectly straight.","SOLO OR PARTY — Play alone or with friends; perfect for game night."],"category":"Toys"}),
  p({"name":"Fisher-Price Rock-a-Stack","slug":"fisher-price-rock-a-stack","description":"Classic baby toy with 5 colorful rings to grasp and stack.","price":349,"comparePrice":499,"brand":"Fisher-Price","stock":180,"rating":4.8,"numReviews":78901,"prime":true,"features":["CLASSIC PLAY — A classic stacking toy with 5 colorful rings to grasp, shake, and stack.","ROCKING BASE — Bat-at rocker base for wobbling fun.","DEVELOPMENTAL — Helps develop hand-eye coordination, dexterity, and problem-solving skills.","SAFE FOR BABIES — Made from plant-based materials and safe for babies ages 6 months and older."],"category":"Toys"}),
];

const seed = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`Seeded ${products.length} products.
`);
  for (const cat of SHOP_CATEGORIES) {
    const count = await Product.countDocuments({ category: cat, isActive: true });
    const ok = count >= MIN_PRODUCTS_PER_CATEGORY ? '✓' : '✗';
    console.log(`  ${ok} ${cat}: ${count} products`);
  }
  process.exit(0);
};

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
